server:
  port: 8080

spring:
  application:
    name: shuttle-demo-v3
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shuttle_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 030913
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:db/mysql/schema.sql
      data-locations: classpath:db/mysql/demo-data.sql

wechat:
  miniapp:
    session-expire-days: 7
